spring.application.name=backend
server.port=${PORT:8081}
node.id=${NODE_ID:2}
# Format: id:host:port,id:host:port
# For local testing: 1:localhost:8081,2:localhost:8082,3:localhost:8083
# For distributed systems: 1:192.168.X.X:8081,2:192.168.X.X:8081,3:192.168.X.X:8081
nodes.all=${NODES_ALL:1:192.168.2.103:8081,2:192.168.2.104:8081,3:192.168.2.97:8081}

logging.level.com.example.backend=INFO
